"""Tests for kidney plot standardization.

Ensures kidney plotting produces the same canonical figure set as benchmarks
by delegating to biorsp.plotting.standard.make_standard_plot_set.
"""

import pandas as pd


def test_kidney_plot_creates_required_filenames(tmp_path):
    """Test that kidney plotting creates canonical figure set."""
    import numpy as np

    from analysis.kidney_atlas.utils.standardized_plotting import generate_kidney_panels

    # Create minimal synthetic scores dataframe
    scores_df = pd.DataFrame(
        {
            "gene": [f"Gene{i}" for i in range(20)],
            "Spatial_Score": np.random.rand(20),
            "Coverage": np.random.uniform(0.1, 0.5, 20),
            "abstain_flag": [False] * 18 + [True] * 2,
        }
    )

    # Generate plots
    generate_kidney_panels(
        scores_df=scores_df,
        labels=None,  # No truth labels for kidney
        output_dir=tmp_path,
        plot_config={"show_truth": False},
    )

    # Verify required files exist (PNGs only - no PDFs generated by make_standard_plot_set)
    required_files = [
        "fig_cs_scatter.png",
        "fig_cs_marginals.png",
        "fig_confusion_or_composition.png",  # Should be composition since no labels
    ]

    for filename in required_files:
        filepath = tmp_path / filename
        assert filepath.exists(), f"Missing required file: {filename}"
        assert filepath.stat().st_size > 1000, f"File too small: {filename}"


def test_kidney_plot_delegate_to_standard():
    """Test that kidney plotting delegates to make_standard_plot_set."""
    # This is an integration test - verify the import works
    from analysis.kidney_atlas.utils.standardized_plotting import make_standard_plot_set

    # Should be importing from biorsp.plotting.standard
    assert make_standard_plot_set.__module__ == "biorsp.plotting.standard"


def test_kidney_plot_no_truth_config():
    """Test that kidney plots default to show_truth=False."""
    from unittest.mock import patch

    from analysis.kidney_atlas.utils.standardized_plotting import generate_kidney_panels

    scores_df = pd.DataFrame(
        {
            "gene": ["Gene1", "Gene2"],
            "Spatial_Score": [0.5, 0.7],
            "Coverage": [0.3, 0.4],
            "abstain_flag": [False, False],
        }
    )

    # Mock make_standard_plot_set to capture config
    with patch(
        "analysis.kidney_atlas.utils.standardized_plotting.make_standard_plot_set"
    ) as mock_plot:
        from pathlib import Path

        generate_kidney_panels(
            scores_df=scores_df,
            labels=None,
            output_dir=Path("/tmp/test"),
            plot_config={},
        )

        # Verify it was called with truth_col=None (no ground truth for kidney data)
        assert mock_plot.called
        call_kwargs = mock_plot.call_args[1]
        assert call_kwargs["truth_col"] is None
        assert call_kwargs["debug"] is False
