"""
Project constants for BioRSP.

Single source of truth for Methods defaults and numeric stabilizers.
"""

import numpy as np

B_DEFAULT = 72
DELTA_DEG_DEFAULT = 60.0
DELTA_RAD_DEFAULT = np.deg2rad(DELTA_DEG_DEFAULT)
SMOOTH_DEG_DEFAULT = 5.0  # Visualization only

N_FG_MIN_DEFAULT = 10
N_BG_MIN_DEFAULT = 50
N_FG_TOT_MIN_DEFAULT = 100
ADEQUACY_FRACTION_DEFAULT = 0.9

MIN_FG_EFF_DEFAULT = 5.0
MIN_BG_EFF_DEFAULT = 10.0
MIN_TOTAL_MF_DEFAULT = 50.0
MIN_COVERAGE_DEFAULT = 0.1
MIN_VALID_SECTORS_DEFAULT = 3

UMI_BINS_DEFAULT = 10  # Q=10
N_R_BINS_DEFAULT = 10
N_THETA_BINS_DEFAULT = 4
MIN_STRATUM_SIZE_DEFAULT = 50
K_EXPLORATORY_DEFAULT = 200
K_FINAL_DEFAULT = 1000
IQR_FLOOR_DEFAULT = 0.1

EPS = 1e-8

REASON_SECTOR_FG_TOO_SMALL = "low_fg"
REASON_SECTOR_BG_TOO_SMALL = "low_bg"
REASON_SECTOR_MIXED_TOO_SMALL = "low_mixed"
REASON_SECTOR_DEGENERATE_SCALE = "degenerate_scale"
REASON_GENE_UNDERPOWERED = "low_total_signal"
REASON_GENE_LOW_COVERAGE = "low_coverage"
REASON_GENE_TOO_FEW_SECTORS = "too_few_valid_sectors"
REASON_OK = "ok"

__all__ = [
    "B_DEFAULT",
    "DELTA_DEG_DEFAULT",
    "DELTA_RAD_DEFAULT",
    "SMOOTH_DEG_DEFAULT",
    "N_FG_MIN_DEFAULT",
    "N_BG_MIN_DEFAULT",
    "N_FG_TOT_MIN_DEFAULT",
    "ADEQUACY_FRACTION_DEFAULT",
    "MIN_FG_EFF_DEFAULT",
    "MIN_BG_EFF_DEFAULT",
    "MIN_TOTAL_MF_DEFAULT",
    "MIN_COVERAGE_DEFAULT",
    "MIN_VALID_SECTORS_DEFAULT",
    "UMI_BINS_DEFAULT",
    "N_R_BINS_DEFAULT",
    "N_THETA_BINS_DEFAULT",
    "MIN_STRATUM_SIZE_DEFAULT",
    "K_EXPLORATORY_DEFAULT",
    "K_FINAL_DEFAULT",
    "EPS",
    "REASON_SECTOR_FG_TOO_SMALL",
    "REASON_SECTOR_BG_TOO_SMALL",
    "REASON_SECTOR_MIXED_TOO_SMALL",
    "REASON_SECTOR_DEGENERATE_SCALE",
    "REASON_GENE_UNDERPOWERED",
    "REASON_GENE_LOW_COVERAGE",
    "REASON_GENE_TOO_FEW_SECTORS",
    "REASON_OK",
]
